project:
  type: website
  resources:
    - "pdf/*.pdf"

website:
  title: "    "  
  sidebar:
    search: false
    style: "floating"
    collapse-level: 0
  #   contents:
        # - text: "Soundtracks"
        #   file: index.qmd
        # - text: Sources
        #   file: bibliography.qmd
  #       - section: "Lectures"
  #         contents:
  #           # Weekly lectures will be added as needed
        # - section: "Soundtracks"
        #   contents:
        #     - text: Pokémon HeartGold & SoulSilver
        #       file: pokemon.qmd
  navbar:
    background: "#235440"
    search: false
    left: 
      - text: "Home"
        file: index.qmd
      - text: Sources
        file: bibliography.qmd
    right:
      - icon: envelope
        aria-label: email
        href: mailto:mrober40@fitchburgstate.edu
      - icon: mastodon
        aria-label: mastodon
        href: https://merveilles.town/@dokoissho
      - icon: github
        aria-label: github
        href: https://github.com/mroberts1/fsu-game-studies-fa25
    # - icon: twitter
    #   aria-label: twitter
    #   href: https://twitter.com/mroberts_fsu
format:
  html:
    # toc: false
    # toc-depth: 2
    # toc-location: right
    # toc-title: '   '
    theme:
      light: [ember.scss, custom_callouts.scss]
      dark: [ember.scss, custom_callouts.scss, slate]
    css: custom.scss
    self-contained: false
    grid:
        sidebar-width: 300px
        body-width: 800px
        margin-width: 300px
        gutter-width: 2em
    linestretch: 1.5
    fontsize: 1.1em
    smooth-scroll: true
    linkcolor: "#235440"
    title-block-banner: false
    link-external-newwindow: true
  PrettyPDF-pdf: default
callout-appearance: default
bread-crumbs: false
fig-responsive: true
image-alt: " "
execute:
  freeze: true
# reference-location: margin
# citation-location: margin
editor: visual
